<?php

/** @var $viewModel SiteTestQualityViewModel */
use DvsaCommon\Enum\VehicleClassGroupCode;
use Site\ViewModel\TestQuality\SiteTestQualityViewModel;

$returnLink = $viewModel->getReturnLink();
?>

<div class="text">
    <p class="lede">This information will help you manage the quality of testing at your site. How you use it will
        depend on how you manage the site, its size and number of staff.</p>
    <h2 class="heading-medium">Tests done in <?php echo $viewModel->getDateRangeWording() ?> </h2>
</div>

<?php

echo $this->partial('site/site/test-quality-information/month-range-form', [
    'form' => $viewModel->getMonthRangeForm(),
]);

if ($viewModel->canGroupSectionBeViewed(VehicleClassGroupCode::BIKES)) {
    echo $this->partial('site/site/test-quality-information/group', [
        'group' => $viewModel->getA(),
        'queryParams' => $viewModel->getQueryParams(),
    ]);
}

if ($viewModel->canGroupSectionBeViewed(VehicleClassGroupCode::CARS_ETC)) {
    echo $this->partial('site/site/test-quality-information/group', [
        'group' => $viewModel->getB(),
        'queryParams' => $viewModel->getQueryParams(),
    ]);
}
?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="return-link"
               href="<?php echo $this->url($returnLink->getRoot(), $returnLink->getParams(), $returnLink->getQueryParams()) ?>">
                <?php echo $returnLink->getValue(); ?>
            </a>
        </li>
    </ul>
</nav>