
<?php
use Site\ViewModel\TestQuality\UserTestQualityViewModel;

/** @var UserTestQualityViewModel $vm */
$vm = $this->viewModel;
?>

<div class="text">
    <h2 class="heading-medium">Tests done in <?php echo $vm->getMonthRange() ?></h2>
</div>

<?php
echo $this->partial('site/site/test-quality-information/month-range-form', [
    'form' => $vm->getMonthRangeForm(),
]);

echo $this->partial('site/site/partials/test-quality-group-breakdown', [
    'group' => $vm->getTable(),
]);
?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="return-link" href="<?php echo $vm->getReturnLink(); ?>">
                Return to test quality information
            </a>
        </li>
    </ul>
</nav>
