<?php
use Dvsa\Mot\Frontend\PersonModule\ViewModel\TestQualityInformation\GroupStatisticsTable;
use Site\ViewModel\TimeSpanFormatter;

/* @var GroupStatisticsTable $group */
/* @var array $queryParams */
?>


<?php
echo $this->partial('tqi/partial/group-header', [
    'group' => $group->getAverageGroupStatisticsHeader()
]);
?>

<table id="tqi-table-<?php echo $group->getGroupCode() ?>">
    <thead>
        <tr>
            <th scope="col">Sites</th>
            <th class="numeric" scope="col">Tests done</th>
            <th class="numeric" scope="col">Average vehicle age</th>
            <th class="numeric" scope="col">Average test time</th>
            <th class="numeric" scope="col">Tests failed</th>
            <th class="numeric" scope="col">Failures by category</th>
        </tr>
    </thead>
    <tbody>

    <?php if ($group->hasTests()) : ?>
        <?php foreach ($group->getSiteTests() as $site): ?>
            <tr>
                <th scope="row">
                    <?php echo $site->getSiteName() ?>
                    <span class="table-summary__meta"><?php echo $site->getSiteAddress() ?></span>
                </th>
                <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                    'hasTests' => true,
                    'notAvailableText' => '0',
                    'value' => $site->getTestsDone(),
                ]); ?>

                <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                    'hasTests' => $site->isAverageVehicleAgeAvailable(),
                    'notAvailableText' => '-',
                    'value' => $site->getAverageVehicleAgeAsString(),
                    'suffix' => 'y',
                ]); ?>

                <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                    'hasTests' => $site->isAverageTestTime(),
                    'notAvailableText' => '-',
                    'value' => (new TimeSpanFormatter())->formatForTestQualityInformationView($site->getAverageTestTime()),
                    'suffix' => 'm',
                ]); ?>

                <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                    'hasTests' => true,
                    'notAvailableText' => '0%',
                    'value' => $site->getTestsFailedPercentage(),
                ]); ?>
                <td class="numeric">
                    <a href="<?php echo $site->getTqiComponentsAtSiteUrl(); ?>">
                        View
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="6">
                No Group <?php echo $group->getGroupCode() ?> tests done
            </td>
        </tr>
    <?php endif ?>


    <?php if ($group->isNationalDataAvailable()): ?>
        <tr>
            <th scope="row">
                National average
            </th>
            <td class="numeric">
                <?php echo $group->getNationalTestCount(); ?>
            </td>
            <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                'hasTests' => $group->getIsNationalDataAvailable(),
                'notAvailableText' => '-',
                'value' => $group->getNationalAverageVehicleAge(),
                'suffix' => 'y'
            ]); ?>
            <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                'hasTests' => $group->getIsNationalDataAvailable(),
                'notAvailableText' => '-',
                'value' => $group->getNationalAverageTestDuration(),
                'suffix' => 'm'
            ]); ?>
            <?php echo $this->partial('tqi/partial/test-quality-group-not-available-check', [
                'hasTests' => $group->getIsNationalDataAvailable(),
                'notAvailableText' => '0%',
                'value' => $group->getNationalPercentageFailed()
            ]); ?>
            <td class="numeric"></td>
        </tr>
    <?php else: ?>
        <tr class="table-reference__row--secondary">
            <td colspan="6">
                National average not available
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>