<?php
use Core\Formatting\AddressFormatter;
use DvsaCommon\Enum\SiteContactTypeCode;

/** @var \DvsaCommon\Dto\Site\VehicleTestingStationDto $site */
$site = $this->viewModel->site;
$siteAddress = null;
if (!is_null($site)) {
    $contact = $site->getContactByType(SiteContactTypeCode::BUSINESS);
    if (!is_null($contact)) {
        $siteAddress = $contact->getAddress();
    }
}

?>
<?php echo $this->partial('errorMessages', array('getFromFlash' => true)); ?>
<h3 class="summary-heading">Certificate details</h3>


<?php
echo $this->partial(
    'partial/gds/gds-table/gds-key-value-table',
    [
        'table' => $this->viewModel->table,
    ]
);
?>

<h3 class="summary-heading">Demo test location</h3>

<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            VTS ID
        </th>
        <td class="key-value-list__value">
            <?php echo $site ? $site->getSiteNumber() : 'Not recorded' ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Vehicle Testing Station
        </th>
        <td class="key-value-list__value">
            <?php echo $site ? $site->getName() : 'Unknown' ?>
            <span class="key-value-list__meta"><?php echo $siteAddress ? (new AddressFormatter())
                    ->setAddressPartsGlue(', ')
                    ->escapedDtoToMultiLine($siteAddress)
                : '' ?></span
        </td>
    </tr>
    </tbody>
</table>

<?php if ($this->viewModel->isViewingHimself): ?>
    <h3 class="heading-medium">
        By confirming these details you agree to the following declaration.
    </h3>
    <div class="message--important">
        <h3 class="message__heading">
            Declaration
        </h3>
        <p>
            I understand that as an authorised MOT tester, I must:
        </p>
        <ul class="list-bullet">
            <li>
                be a skilled mechanic with at least 4 years’ full-time employment servicing and repairing the types of vehicles I’m going to test
            </li>
            <li>
                have a current and full UK driving licence for the vehicle classes I want to test
            </li>
            <li>
                notify the Authorised Examiner at my testing station if my driving licence is suspended or restricted
            </li>
            <li>
                have no unspent criminal convictions related to the motor trade or involving acts of violence or intimidation
            </li>
            <li>
                notify DVSA in the future if I gain any criminal convictions of this type
            </li>
            <li>
                never harass, bully, verbally or physically abuse, or discriminate against any employee of DVSA or person acting on its behalf
            </li>
            <li>
                be ‘of good repute’ - DVSA will decide this to make sure I’m suitable to be an MOT tester
            </li>
            <li>
                make sure that personal details on my MOT testing service user profile, including email address, personal address and phone number, are kept up to date
            </li>
            <li>
                carry out all MOT tests to the requirements of Section 45 of the Road Traffic Act 1988, the Motor Vehicles (Tests) Regulations, the MOT inspection manual, the MOT testing guide, and additional information issued from time to time by DVSA
            </li>
        </ul>
        <p>
            I am aware that I may be disqualified from testing if DVSA discovers I haven’t met these terms.
        </p>
    </div>
    <p>
        After you confirm we’ll be in touch to arrange a demo test.
    </p>
<?php endif ?>

<form novalidate="" autocomplete="off" method="POST" action="">
    <?php echo $this->csrfToken(); ?>

    <nav class="content-navigation">
        <input type="submit" class="button" value="Confirm details" id="confirm-button">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->viewModel->backUrl ?>"><?php echo $this->viewModel->backUrlText ?></a>
            </li>
        </ul>
    </nav>
</form>
