<?php

/* @var \UserAdmin\Presenter\PersonPresenter[] $users */
/* @var string $userProfileRoute */
/* @var array $userSearchCriteria */

use UserAdmin\Controller\UserSearchController;

?>

<table id="results" class="table">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <?php if ($userSearchExtended): ?>
            <th scope="col">Username</th>
        <?php endif; ?>

            <th scope="col">Date of birth</th>

        <th scope="col">Address</th>
        <th scope="col">Postcode</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
        <tr data-element="result-details">
            <td data-element="result-username">

                <form action="<?php echo $this->url('newProfileUserAdmin',
                        [
                            'id' => $user->getPersonId(),
                        ]); ?>" method="POST">

                    <?php echo $this->csrfToken() ?>

                    <input type="hidden" name="<?php echo UserSearchController::PARAM_USERNAME; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_USERNAME]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_FIRSTNAME; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_FIRSTNAME]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_LASTNAME; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_LASTNAME]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_EMAIL; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_EMAIL]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_DOB; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_DOB]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_DOB_YEAR; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_DOB_YEAR]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_DOB_MONTH; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_DOB_MONTH]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_DOB_DAY; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_DOB_DAY]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_TOWN; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_TOWN]; ?>" />
                    <input type="hidden" name="<?php echo UserSearchController::PARAM_POSTCODE; ?>" value="<?php echo $userSearchCriteria[UserSearchController::PARAM_POSTCODE]; ?>" />
                    <input type="submit" class="button--link" value="<?php echo $this->escapeHtml($user->displayFullName()); ?>" />
                </form>


            </td>
            <?php if ($userSearchExtended): ?>
                <td data-element="result-user-username"><?php echo $this->escapeHtml($user->displayUsername()); ?></td>
            <?php endif; ?>

                <td data-element="result-user-dob"><?php echo $this->escapeHtml($user->displayUserDateOfBirth()); ?></td>

            <td data-element="result-user-address"><?php echo $this->escapeHtml($user->displayUserAddress()); ?></td>
            <td data-element="result-user-postcode"><?php echo $this->escapeHtml($user->displayPostcode()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
