<?php
use Csrf\CsrfConstants;
use Dvsa\Mot\Frontend\AuthenticationModule\Form\LoginForm;

/**
 * @var $form LoginForm
 * @var
 * @var bool      $authError
 * @var bool      $twoFaEnabled
 */
if ($authError) {
    $this->gtmDataLayer(['event' => 'user-login-failed', 'reason' => 'wrong-username-or-password']);
}

$this->headTitle('Sign in');

?>
<div class="grid-row">
    <div class="__sign-in">
        <?php if (!$authError) : ?>
            <?php echo $this->partial('zendFormErrorMessages', ['form' => $form]); ?>
        <?php else : ?>
            <div id="validationBox">
                <div id="validationErrors" class="validation-summary">
                    <ol>There was a problem with your User ID or password.
                        <br/> Please try again.</ol>
                </div>
            </div>
        <?php endif; ?>
    <div class="column-half">
        <form id="Login" name="Login" action="<?php echo $this->url('login'); ?>" method="post" autocomplete="new-password">
            <fieldset>
                <legend class="form-title heading-large">Sign in</legend>
                <input type="text" id="IDToken1" name="IDToken1" value="" class="form-control
                form-control-1-2" tabindex="-1" style="width: 1px; position: absolute; left: -9999px;">
                <input type="password" id="IDToken2" name="IDToken2" autocomplete="off" value="" class="form-control
                form-control-1-2" tabindex="-1" style="width: 1px; position: absolute; left: -9999px;">
                <?php
                    echo $this->partial(
                        'partial/gds/form/control',
                        [
                            'element' => $usernameField,
                        ]
                    );
                    echo $this->partial(
                        'partial/gds/form/control',
                        [
                            'element' => $passwordField,
                        ]
                    );
                ?>
                <input type="hidden" name="<?php echo CsrfConstants::REQ_TOKEN; ?>" value="<?php echo $csrfToken; ?>">
                <input type="hidden" id="goto" name="goto" value="<?php echo $this->escapeHtmlAttr($this->gotoUrl) ?>"/>
            </fieldset>
            <a id="forgotten-or-change-password" href="<?php echo $this->url('forgotten-password') ?>">Forgotten your password?</a>
            <nav class="content-navigation">
                <input type= "submit" class="button" name="Login.Submit" value="Sign in">
            </nav>
            <input name="IDButton" type="hidden" style="display: none;">
        </form>
    </div>
    </div>
    <div class="column-half">
        <h3 class="heading-medium">Sign in help</h3>
        <?php if ($twoFaEnabled): ?>
            <details role="group">
                <summary role="button" aria-controls="details-content-3" aria-expanded="false" tabindex="0">
                    <span class="summary">Lost, forgotten or damaged security card</span>
                </summary>
                <div class="panel panel-indent" id="details-content-3" aria-hidden="true" >
                    <p>Sign in with your user ID and password. You’ll then see an option to sign in without your card and order a new one if you need to.</p>
                </div>
            </details>
        <?php endif; ?>
        <details role="group">
            <summary role="button" aria-controls="details-content-0" aria-expanded="false" tabindex="0">
                <span class="summary" id="do-not-have-account-section">Don't have an account</span>
            </summary>
            <div class="panel panel-indent" id="details-content-0" aria-hidden="true">
                <p><a id="create-an-account" href="<?php echo $this->url('account-register') ?>">Create a new account</a> for the MOT testing service. Only do this if you don’t already have one.</p>
            </div>
        </details>
    </div>
</div>
