<div class="multiple-choice"
    <?php  if(isset($ariaContainer)) : ?>
        data-target="<?php echo $this->escapeHtmlAttr($ariaContainer); ?>"
    <?php endif; ?>
>

    <input type="radio"
        value="<?php echo $this->escapeHtmlAttr($value); ?>"
        name="<?php echo $this->escapeHtmlAttr($name); ?>"
        id="<?php echo $this->escapeHtmlAttr($id); ?>"
        <?php echo (isset($ariaContainer)) ? ' aria-controls="'.$this->escapeHtmlAttr($ariaContainer).'"' : '' ?>
        <?php echo ($this->checked === strval($value)) ? ' checked="checked"' : '' ?> />

    <label class="<?php echo isset($labelClass) ? ' ' . $labelClass : '';?>"
           for="<?php echo $this->escapeHtmlAttr($id); ?>">
        <?php echo $this->escapeHtmlAttr($title); ?>
        <?php if (isset($meta)) : ?>
            <span class="block-label__meta"><?php echo $this->escapeHtmlAttr($meta); ?></span>
        <?php endif; ?>
    </label>

</div>